Repository softeer5th/Team7-BungeoBbang, pull requests merged in 2025-01, with the labels that each got.

#31 [Feat/BE/#29] 도메인 세팅
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/admin/domain/Admin.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaImage.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaMember.java
  backend/src/main/java/com/bungeobbang/backend/common/entity/BaseTimeEntity.java
  backend/src/main/java/com/bungeobbang/backend/common/type/CategoryType.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/Member.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/ProviderType.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionType.java
  backend/src/main/java/com/bungeobbang/backend/university/domain/University.java
  backend/src/main/resources/application-local.yml
Labels: BE

#37 [Feat/BE/#36] global exception 설정
  backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/response/ErrorResponse.java
Labels: BE

#39 [Feat/BE/#32] 카카오 소셜 로그인
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/BackendApplication.java
  backend/src/main/java/com/bungeobbang/backend/common/config/RedisConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/config/RestTemplateConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/AuthException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/RedisClient.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/Member.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/MemberTokens.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/OauthAccessToken.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/ProviderType.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/repository/MemberRepository.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/MemberLoginResult.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/response/MemberLoginResponse.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthprovider/KakaoOauthProvider.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthprovider/OauthProvider.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthprovider/OauthProviders.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthuserinfo/KakaoUserInfo.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthuserinfo/OauthUserInfo.java
  backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/test/java/com/bungeobbang/backend/member/presentation/MemberControllerTest.java
Labels: BE, STUDENT

#41 [Feat/BE/#33] 관리자 로그인 API 구현
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/admin/config/BCryptPasswordEncoder.java
  backend/src/main/java/com/bungeobbang/backend/admin/config/PasswordEncoder.java
  backend/src/main/java/com/bungeobbang/backend/admin/config/SecurityConfig.java
  backend/src/main/java/com/bungeobbang/backend/admin/domain/Admin.java
  backend/src/main/java/com/bungeobbang/backend/admin/domain/repository/AdminRefreshTokenRepository.java
  backend/src/main/java/com/bungeobbang/backend/admin/domain/repository/AdminRepository.java
  backend/src/main/java/com/bungeobbang/backend/admin/dto/request/AdminLoginRequest.java
  backend/src/main/java/com/bungeobbang/backend/admin/presentation/AdminLoginController.java
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/response/MemberLoginResult.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/response/MemberTokens.java
  backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
Labels: BE, FEATURE⚡️, ADMIN

#44 [Feat/BE/#27] 학생 로그인 구현
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/BackendApplication.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/mail/domain/repository/EmailVerificationCodeRepository.java
  backend/src/main/java/com/bungeobbang/backend/mail/dto/request/EmailVerificationRequest.java
  backend/src/main/java/com/bungeobbang/backend/mail/dto/request/SendVerificationMailRequest.java
  backend/src/main/java/com/bungeobbang/backend/mail/presentation/EmailAuthController.java
  backend/src/main/java/com/bungeobbang/backend/mail/service/EmailAuthService.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthprovider/GoogleOauthProvider.java
  backend/src/main/java/com/bungeobbang/backend/member/infrastructure/oauthuserinfo/GoogleUserInfo.java
  backend/src/main/java/com/bungeobbang/backend/university/domain/repository/UniversityRepository.java
  backend/src/main/java/com/bungeobbang/backend/university/dto/response/UniversityResponse.java
  backend/src/main/java/com/bungeobbang/backend/university/presentation/UniversityController.java
  backend/src/main/java/com/bungeobbang/backend/university/service/UniversityService.java
  backend/src/main/resources/templates/email-template.html
  backend/src/test/java/com/bungeobbang/backend/mail/service/EmailAuthServiceTest.java
Labels: BE, FEATURE⚡️, STUDENT

#51 [FEAT/FE/#30] 공통 컴포넌트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/arrow_left.svg
  frontend/src/assets/icons/arrow_up.svg
  frontend/src/assets/icons/camera.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/logout.svg
  frontend/src/assets/imgs/preview_img.png
  frontend/src/assets/react.svg
  frontend/src/components/BorderProps.tsx
  frontend/src/components/BottomNavigation/BottomNavigation.tsx
  frontend/src/components/BottomNavigation/BottomNavigationItem.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Chat/ChatSendField.tsx
  frontend/src/components/Chat/ReceiverChat.tsx
  frontend/src/components/Chat/SenderChat.tsx
  frontend/src/components/Chat/TextBadge.tsx
  frontend/src/components/Chip/ChipList.tsx
  frontend/src/components/Chip/ChipListItem.tsx
  frontend/src/components/Dialog.tsx
  frontend/src/components/IconLoadingBox.tsx
  frontend/src/components/TextField/CountTextField.tsx
  frontend/src/components/TextField/TextField.tsx
  frontend/src/components/TopAppBar.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/Typography.tsx
  frontend/src/styles/font/Pretendard-Bold.woff
  frontend/src/styles/font/Pretendard-Medium.woff
  frontend/src/styles/font/Pretendard-SemiBold.woff
  frontend/src/styles/theme.ts
  frontend/src/types/svg.d.ts
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  package-lock.json
Labels: FE, FEATURE⚡️

#57 [Fix/BE/#27] 도커 환경에서 이메일 템플릿 읽지 못하는 오류 수정
  backend/src/main/java/com/bungeobbang/backend/mail/service/EmailAuthService.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/request/MemberUniversityUpdateRequest.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/request/SocialLoginRequest.java
  backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
Labels: BE
