Repository softeer5th/Team7-BungeoBbang, pull requests merged in 2025-02, with the labels that each got.

#76 [Fix/BE/#70] 말해요 api 1차 merge
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/auth/Auth.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/Accessor.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/Authority.java
  backend/src/main/java/com/bungeobbang/backend/common/config/LoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/OpinionException.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/BearerAuthorizationExtractor.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/LoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/request/OpinionCreationRequest.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionCreationResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionStatisticsResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BE, FEATURE⚡️, STUDENT

#86 [Feat/BE/#71] agenda 답해요 생성,수정,삭제,종료 API
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaImage.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaImageRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaCreationRequest.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaEditRequest.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaCreationResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminAuth.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminOnly.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminOnlyChecker.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/Accessor.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/AdminException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/AgendaException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/main/resources/application-local.yml
Labels: BE

#85 [Fix/BE/#70] 말해요 학생 api 구현
  backend/src/main/java/com/bungeobbang/backend/common/config/MongoConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/CommonException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/type/CategoryType.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionLastRead.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionType.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionLastReadRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoListResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionCreationResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BE, FEATURE⚡️, STUDENT

#91 [Feat/BE/#90] 학생 인가 로직 구현
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/auth/BearerAuthorizationExtractor.java
  backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/Auth.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberLoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberOnly.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberOnlyChecker.java
  backend/src/main/java/com/bungeobbang/backend/common/config/LoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
Labels: BE

#98 [Feat/Be/#94] 답해요 채팅방 조회 API
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/ActiveAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/AgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/AgendaFinders.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/ClosedAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/UpcomingAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/status/AgendaStatusType.java
  backend/src/main/java/com/bungeobbang/backend/common/config/QuerydslConfig.java
Labels: BE, FEATURE⚡️

#96 [Feat/BE/#95] 학생 말해요 채팅방 리스트 조회 수정
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoListResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionStatisticsResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BE, REFACTOR, STUDENT

#102 [Feat/BE/#99] 학생이 참여한 답해요 채팅방 목록 조회 API
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastReadChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/MyAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
Labels: BE, FEATURE⚡️, STUDENT

#116 [Feat/BE/#70] 말해요 채팅(학생&학생회) 내역 조회, 채팅방 리스트(학생회) 조회 API
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoListResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionChatResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/AdminOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/MemberOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BE, FEATURE⚡️, STUDENT, ADMIN

#118 [Test/BE/#117] 답해요 테스트 코드
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/BackendApplication.java
  backend/src/main/java/com/bungeobbang/backend/admin/domain/Admin.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaLastReadChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaLastReadChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/MyAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/common/config/AsyncConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/config/CorsConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/config/JpaAuditingConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/member/domain/Member.java
  backend/src/main/java/com/bungeobbang/backend/university/domain/University.java
  backend/src/test/java/com/bungeobbang/backend/admin/fixture/AdminFixture.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/fixture/AgendaFixture.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/member/fixture/MemberFixture.java
  backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/university/UniversityFixture.java
  backend/src/test/resources/data/agenda.sql
  backend/src/test/resources/data/agenda_chat.json
  backend/src/test/resources/data/common.sql
Labels: BE

#127 [Refactor/BE#55] RedisClient 변경
  backend/src/main/java/com/bungeobbang/backend/common/config/RedisConfig.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/RedisClient.java
Labels: BE, SETTING

#150 [Feat/BE/#121] websocket
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaChatRequest.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/config/WebSocketConfig.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AdminConnectEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AdminWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaAdminEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaMemberEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberConnectEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/MessageQueueService.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/RedisMessageQueue.java
  backend/src/main/java/com/bungeobbang/backend/chat/type/RoomType.java
  backend/src/main/java/com/bungeobbang/backend/chat/type/SocketEventType.java
  backend/src/main/java/com/bungeobbang/backend/common/config/ObjectMapperConfig.java
  backend/src/main/resources/application-local.yml
Labels: BE, FEATURE⚡️

#154 [Fix/BE/#151] 답해요 채팅 정렬 순서 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaAdminLastReadChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AdminLastReadChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaLastReadChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
Labels: BE, FIX

#153 [Feat/BE/#149] 말해요 채팅방 리스트 성능개선, workflow 추가
  .github/workflows/gradle.yml
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionLastReadRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
Labels: BE, REFACTOR, SETTING

#159 [Fix/BE] workflow 수정
  .github/workflows/gradle.yml
Labels: BE, SETTING, FIX

#158 [Feat/BE/#121] agenda websocket
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaChatRequest.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaDetailResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AdminWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaAdminEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaMemberEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/MessageQueueService.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/RedisMessageQueue.java
  backend/src/main/java/com/bungeobbang/backend/chat/type/SocketEventType.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
Labels: BE, FEATURE⚡️

#162 [Feat/BE/#161] 말해요 api 수정
  .github/workflows/gradle.yml
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionDetailResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BE, FEATURE⚡️, STUDENT, ADMIN

#166 [Feat/BE/#120] 답해요 첫번째 채팅 저장 & CI 스크립트 작성
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/test/java/com/bungeobbang/backend/BackendApplicationTests.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/member/presentation/MemberControllerTest.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/application.yml
Labels: BE

#168 [Feat/BE/#167] 중복 로그인 방지 로직 구현
  .github/workflows/be-ci.yml
  backend/src/main/java/com/bungeobbang/backend/admin/domain/repository/AdminRefreshTokenRepository.java
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/repository/RefreshTokenRepository.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/repository/UuidRepository.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/UuidException.java
  backend/src/main/java/com/bungeobbang/backend/common/infrastructure/RedisClient.java
  backend/src/main/java/com/bungeobbang/backend/mail/domain/repository/EmailVerificationCodeRepository.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
Labels: BE

#174 [Hotfix/BE]웹소켓 어세스토큰 extract 수정
  backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java
Labels: FIX

#175 [Feat/BE] sockJS 추가
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/chat/config/WebSocketConfig.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
Labels: BE

#182 [Refactor/BE/#172] 답해요 리팩토링
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaAdminLastReadChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AdminAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaLatestChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastReadChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/repository/RefreshTokenRepository.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/repository/UuidRepository.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
Labels: BE

#187 [FEAT/FE/178] 학생 답해요 채팅방 입장, 퇴장
  frontend/src/components/TopAppBar.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx
  frontend/src/domains/admin/pages/chat-page/index.tsx
  frontend/src/domains/admin/pages/chat-page/styles.ts
  frontend/src/domains/student/pages/agenda/chat/index.tsx
  frontend/src/domains/student/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/student/pages/agenda/data/ChatRoomListCardData.tsx
  frontend/src/domains/student/pages/agenda/index.tsx
  frontend/src/domains/student/pages/agenda/util/ChatRoomCardMapper.tsx
  frontend/src/domains/student/pages/chat-page/ChatData.tsx
  frontend/src/domains/student/pages/chat-page/index.tsx
  frontend/src/domains/student/pages/opinion/chatroom/index.tsx
  frontend/src/main.tsx
  frontend/src/utils/chat/formatChatData.ts
Labels: FE, FEATURE⚡️, STUDENT

#190 [Feat/BE/#189] 답해요 레디스 구독 관리
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminDisconnectEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberDisconnectEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/service/RedisMessageQueue.java
Labels: BE

#192 [Test/BE/#186] 말해요 api 테스트 작성
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/auth/domain/repository/UuidRepository.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminDisconnectEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionLastRead.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionChatFixture.java
  backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionFixture.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: BE, FIX

#194 [Feat/BE/#193] 채팅 전송 시 종료/삭제 여부 검증
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaAdminEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaMemberEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
Labels: BE, FEATURE⚡️

#196 [Feat/BE/#193] 말해요 채팅방 삭제에 대한 검증
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/common/Auth.java
  backend/src/main/java/com/bungeobbang/backend/auth/common/LoginArgumentResolver.java
  backend/src/main/java/com/bungeobbang/backend/auth/common/LoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/Auth.java
  backend/src/main/java/com/bungeobbang/backend/auth/member/MemberLoginResolverConfig.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionAdminEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionMemberEvent.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/AdminOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/MemberOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionFixture.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: BE

#201 [Feat/BE/#198] 답해요 채팅방 무한 스크롤 양방향 지원
  backend/src/main/java/com/bungeobbang/backend/admin/dto/response/AdminLoginResponse.java
  backend/src/main/java/com/bungeobbang/backend/admin/dto/response/AdminLoginResult.java
  backend/src/main/java/com/bungeobbang/backend/admin/presentation/AdminLoginController.java
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AdminAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaLastReadChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/MemberAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/AdminAgendaSubResult.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/AgendaLatestChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/MemberAgendaSubResult.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/admin/AdminAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/member/MemberAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/member/MyAgendaResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/ActiveAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/AgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/ClosedAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/strategies/UpcomingAgendaFinder.java
  backend/src/main/java/com/bungeobbang/backend/common/type/ScrollType.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/AdminOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
Labels: BE, FEATURE⚡️

#199 [FEAT/FE/188] 답해요 채팅방 목록 무한 스크롤
  frontend/src/components/Chat/ChatSendField.tsx
  frontend/src/components/Chat/ReceiverChat.tsx
  frontend/src/components/Chat/SenderChat.tsx
  frontend/src/components/Chat/TextBadge.tsx
  frontend/src/components/Chip/ChipList.tsx
  frontend/src/components/Chip/ChipListItem.tsx
  frontend/src/components/TopAppBar.tsx
  frontend/src/components/bottom-navigation/BottomNavigation.tsx
  frontend/src/components/tab-bar/TabBarItem.tsx
  frontend/src/components/text-field/CountTextField.tsx
  frontend/src/components/text-field/TextField.tsx
  frontend/src/domains/admin/App.tsx
  frontend/src/domains/admin/pages/agenda/components/AgendaDeleteDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatEndDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/admin/pages/agenda/create/index.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx
  frontend/src/domains/admin/pages/destinations.tsx
  frontend/src/domains/admin/pages/opinion/entry/index.tsx
  frontend/src/domains/student/pages/agenda/components/ChatEnterDialog.tsx
  frontend/src/domains/student/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/student/pages/agenda/data/ChatRoomListCardData.tsx
  frontend/src/domains/student/pages/agenda/index.tsx
  frontend/src/domains/student/pages/agenda/util/ChatRoomCardMapper.tsx
  frontend/src/domains/student/pages/destinations.tsx
  frontend/src/domains/student/pages/my/index.tsx
  frontend/src/domains/student/pages/my/styles.ts
  frontend/src/domains/student/pages/opinion/entry/index.tsx
  frontend/src/domains/student/pages/statistics/index.tsx
  frontend/src/domains/student/pages/statistics/styled.ts
  frontend/src/hooks/useInfiniteScroll.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/ChatCategoryType.tsx
Labels: FE

#204 [Feat/BE/#203] 배포 cors 추가
  backend/src/main/java/com/bungeobbang/backend/common/config/CorsConfig.java
Labels: BE

#205 [Fix/BE] 학생회 채널 구독 최적화
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
Labels: BE

#208 [FEAT/FE/200] 내 질문 api 연결
  frontend/src/components/Button.tsx
  frontend/src/components/Chat/ChatSendField.tsx
  frontend/src/components/Chip/ChipList.tsx
  frontend/src/components/Chip/ChipListItem.tsx
  frontend/src/components/Dialog/Dialog.tsx
  frontend/src/components/TopAppBar.tsx
  frontend/src/components/border/BorderProps.tsx
  frontend/src/components/border/getBorderType.tsx
  frontend/src/components/bottom-navigation/BottomNavigation.tsx
  frontend/src/components/readme.md
  frontend/src/components/text-field/CountTextField.tsx
  frontend/src/components/text-field/TextField.tsx
  frontend/src/domains/admin/pages/opinion/entry/OpinionItem.tsx
  frontend/src/domains/admin/pages/opinion/entry/index.tsx
  frontend/src/domains/admin/pages/opinion/entry/styles.ts
  frontend/src/domains/admin/pages/opinion/entry/types.ts
  frontend/src/domains/student/pages/destinations.tsx
  frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx
  frontend/src/domains/student/pages/my/data/ChatPreviewData.tsx
  frontend/src/domains/student/pages/my/index.tsx
  frontend/src/domains/student/pages/my/util/AgendaChatRoomMapper.tsx
  frontend/src/domains/student/pages/opinion/category/components/OpinionStep.tsx
  frontend/src/types/ChatOpinionType.tsx
  frontend/src/utils/findChatCategoryType.ts
  frontend/src/utils/findChatOpinionType.ts
Labels: FE

#216 [Feat/BE/#215] 말해요 채팅 조회 로직 수정
  backend/Dockerfile
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionFixture.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: BE, FEATURE⚡️, STUDENT, ADMIN

#220 [Feat/BE/#218] 답해요 생성/수정 시 금칙어 필터링, 참가하기 동시성 제어
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java
  backend/src/main/java/com/bungeobbang/backend/member/dto/request/MemberUniversityUpdateRequest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceConcurrencyTest.java
  backend/src/test/resources/data/agenda_participate_test.sql
Labels: BE

#226 [FEAT/FE/214] 학생회 답해요 채팅방 위아래로 무한 스크롤
  frontend/src/components/BottomSheet.tsx
  frontend/src/components/Chat/ChatSendField.tsx
  frontend/src/components/Chat/ReceiverChat.tsx
  frontend/src/components/Chat/SenderChat.tsx
  frontend/src/components/Chat/TextBadge.tsx
  frontend/src/domains/admin/App.tsx
  frontend/src/domains/admin/pages/agenda/chat/index.tsx
  frontend/src/domains/admin/pages/agenda/components/CategoryContent.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomCardData.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/admin/pages/agenda/components/MoreContent.tsx
  frontend/src/domains/admin/pages/agenda/components/SubTitleText.tsx
  frontend/src/domains/admin/pages/agenda/create/index.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx
  frontend/src/domains/admin/pages/chat-page/ChatData.tsx
  frontend/src/domains/admin/pages/chat-page/index.tsx
  frontend/src/domains/admin/pages/login/index.tsx
  frontend/src/domains/admin/pages/login/styles.ts
  frontend/src/domains/student/pages/agenda/chat/index.tsx
  frontend/src/domains/student/pages/agenda/index.tsx
  frontend/src/domains/student/pages/my/index.tsx
  frontend/src/hooks/useInfiniteScroll.tsx
  frontend/src/utils/chat/formatChatData.ts
Labels: FE

#230 [Fix/BE/#229] 마지막 읽은 채팅 버그 수정
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionLastReadRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: BUG🐛, BE

#231 [FixBE] s3 role 강제 사용
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java
Labels: BUG🐛, BE

#234 [Feat/BE/#233] 말해요 통계 기능 추가
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/AnsweredOpinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/AnsweredOpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomAnsweredOpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionStatisticsResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/AdminOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: BE, FEATURE⚡️, ADMIN

#238 [FEAT/FE/228] 채팅 목록 위아래로 무한 스크롤
  frontend/src/components/Chat/ReceiverChat.tsx
  frontend/src/components/Chat/SenderChat.tsx
  frontend/src/domains/admin/pages/agenda/chat/index.tsx
  frontend/src/domains/admin/pages/chat-page/index.tsx
  frontend/src/hooks/useScrollBottom.tsx
  frontend/src/utils/chat/formatChatData.ts
Labels: FE

#252 [Fix/BE/#239] 실시간으로 읽고 있을 때 최신데이터 반환
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
Labels: BE

#257 [Feat/BE/#250] 말해요 api 수정
  backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionFixture.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: BE, STUDENT, ADMIN

#266 [ Fix/BE/#265] 말해요 진입페이지 통계 로직 수정
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionStatisticsResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/MemberOpinionApi.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
Labels: BE, STUDENT, FIX

#268 [Fix/BE] agenda last chat createdAt 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaMember.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
Labels: BE, STUDENT

#270 [Fix/BE] : 채팅 내역 조회 스크롤 수정
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
Labels: BE, FIX

#271 [Fix/BE] agenda update 채팅 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminAgendaServiceTest.java
Labels: BE

#279 [Feat/BE] pong 응답, 에러코드 추가
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/type/SocketEventType.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
Labels: BE, FEATURE⚡️

#304 [FEAT/FE/212] 채팅방 추가 관련 오류,예외 처리 & 채팅방 관련 예외 처리
  frontend/src/components/Chat/ChatSendField.tsx
  frontend/src/components/ChatToast.tsx
  frontend/src/components/text-field/CountTextField.tsx
  frontend/src/components/text-field/TextField.tsx
  frontend/src/domains/admin/pages/agenda/chat/chat-page/ChatData.tsx
  frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/admin/pages/agenda/chat/index.tsx
  frontend/src/domains/admin/pages/agenda/components/BadWordErrorDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/admin/pages/agenda/components/DurationContent.tsx
  frontend/src/domains/admin/pages/agenda/components/SameDataErrorDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/SendDialog.tsx
  frontend/src/domains/admin/pages/agenda/create/index.tsx
  frontend/src/domains/admin/pages/opinion/chatroom/index.tsx
  frontend/src/domains/student/pages/agenda/chat/chat-page/ChatData.tsx
  frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx
  frontend/src/domains/student/pages/opinion/chatroom/index.tsx
  frontend/src/hooks/useInfiniteScroll.tsx
  frontend/src/utils/chat/chat_const.ts
  frontend/src/utils/chat/formatChatData.ts
Labels: FE

#289 [Feat/Be/#288] 금칙어 필터링 1차 구현
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/badword/AhoCorasick.java
  backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java
Labels: BE

#309 [Feat/BE/#308] 웹소켓 테스트 코드, 답해요 통계
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/admin/AgendaCategoryResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/admin/AgendaStatisticResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaValidService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/fixture/AgendaFixture.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminMemberAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaValidServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/MemberAgendaServiceConcurrencyTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/MemberAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/data/agenda.sql
  backend/src/test/resources/data/agenda_chat_scroll.json
  backend/src/test/resources/data/agenda_participate_test.sql
  backend/src/test/resources/data/member_agenda_chat_scroll.json
Labels: BE, STUDENT

#315 [Fix/BE] 답해요 종료 로직 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/fixture/AgendaFixture.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminMemberAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketTest.java
  backend/src/test/resources/data/agenda.sql
  backend/src/test/resources/data/agenda_participate_test.sql
Labels: BUG🐛, BE

#334 [Fix/BE/#333] 학생 답해요 상태별 조회 버그 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaValidService.java
  backend/src/test/java/com/bungeobbang/backend/chat/AdminAgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketConcurrencyTest.java
  backend/src/test/resources/data/member.sql
Labels: BUG🐛, BE, STUDENT

#347 [HotFix/BE] 학생회 진행중 안건 구독 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
Labels: BUG🐛, BE, ADMIN

#349 [Fix/BE] 학생 내 답해요 조회 진행안건 버그 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaService.java
Labels: BUG🐛, BE, STUDENT

#354 [Feat/BE/#352] 금칙어 키워드 추출
  backend/src/main/java/com/bungeobbang/backend/badword/AhoCorasick.java
  backend/src/main/java/com/bungeobbang/backend/badword/domain/AllowedWord.java
  backend/src/main/java/com/bungeobbang/backend/badword/domain/repository/AllowedWordRepository.java
  backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/BadWordException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
Labels: BE, FEATURE⚡️

#356 [FIX/BE] 테스트코드 수정
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImplTest.java
  backend/src/test/resources/data/member_agenda_chat_scroll.json
Labels: BE, FIX

#364 [FEAT/FE/361] 탭바 슬라이딩
  frontend/src/components/tab-bar/TabBar.tsx
  frontend/src/components/tab-bar/TabBarCotainer.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/agenda/styles.ts
  frontend/src/domains/admin/pages/statistics/index.tsx
  frontend/src/domains/student/pages/my/index.tsx
  frontend/src/domains/student/pages/my/styles.ts
  frontend/src/stories/TabBar.stories.tsx
  frontend/src/stories/TabBarContainer.stories.tsx
Labels: FE

#375 [Feat/BE/#374] s3 presigned url 발급
  backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java
  backend/src/main/java/com/bungeobbang/backend/image/dto/request/PresignedUrlRequest.java
  backend/src/main/java/com/bungeobbang/backend/image/dto/response/PresignedUrlResponse.java
  backend/src/main/java/com/bungeobbang/backend/image/infrastrcture/S3ImageService.java
  backend/src/main/java/com/bungeobbang/backend/image/presentation/ImageController.java
  backend/src/main/java/com/bungeobbang/backend/image/service/ImageService.java
Labels: BE, FEATURE⚡️

#379 [FEAT/FE/376] 소켓 데이터 추가 최적화
  frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/admin/pages/opinion/chatroom/index.tsx
  frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/student/pages/opinion/chatroom/index.tsx
Labels: FE

#382 [FEAT/FE/#377] presigned url S3 image upload
  frontend/src/hooks/useImageUpload.ts
Labels: FE, FEATURE⚡️

#387 [5차 스프린트]
  backend/build.gradle
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/admin/AgendaCategoryResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/admin/AgendaStatisticResponse.java
  backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaValidService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/badword/AhoCorasick.java
  backend/src/main/java/com/bungeobbang/backend/badword/domain/AllowedWord.java
  backend/src/main/java/com/bungeobbang/backend/badword/domain/repository/AllowedWordRepository.java
  backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/BadWordException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/response/ErrorResponse.java
  backend/src/main/java/com/bungeobbang/backend/image/dto/request/PresignedUrlRequest.java
  backend/src/main/java/com/bungeobbang/backend/image/dto/response/PresignedUrlResponse.java
  backend/src/main/java/com/bungeobbang/backend/image/infrastrcture/S3ImageService.java
  backend/src/main/java/com/bungeobbang/backend/image/presentation/ImageController.java
  backend/src/main/java/com/bungeobbang/backend/image/service/ImageService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/fixture/AgendaFixture.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminMemberAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaValidServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/MemberAgendaServiceConcurrencyTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/service/MemberAgendaServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AdminAgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketConcurrencyTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/data/agenda.sql
  backend/src/test/resources/data/agenda_chat_scroll.json
  backend/src/test/resources/data/member.sql
  backend/src/test/resources/data/member_agenda_chat_scroll.json
Labels: BE

#394 [Feat/BE/#393] opinion 생성 시 웹소켓 이벤트 전송
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/auth/Claim.java
  backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionCreationEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AdminAgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketConcurrencyTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
Labels: BE, FEATURE⚡️

#395 [Fix/BE/#393] opinion enter 구독 삭제
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
Labels: BUG🐛, BE

#397 [FIX/FE/392] socket rendering 에러
  frontend/src/components/Chat/ReceiverChat.tsx
  frontend/src/components/Chat/SenderChat.tsx
  frontend/src/components/Toast/ChatToast.tsx
  frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/admin/pages/agenda/components/AgendaDeleteDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/BadWordErrorDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatEndDialog.tsx
  frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx
  frontend/src/domains/admin/pages/agenda/components/SameDataErrorDialog.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/opinion/chatroom/index.tsx
  frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/student/pages/agenda/components/ChatEnterDialog.tsx
  frontend/src/domains/student/pages/opinion/chatroom/index.tsx
  frontend/src/hooks/useInfiniteScroll.tsx
  frontend/src/stories/Dialog.stories.tsx
  frontend/src/utils/chat/chat_const.ts
Labels: FE, FIX

#406 [FIX/FE/405] 채팅방 추가 이미지 중복 현상
  frontend/src/domains/admin/pages/agenda/create/index.tsx
  frontend/src/hooks/useImageUpload.ts
Labels: BUG🐛, 👔FE, 🛠️FIX

#411 [Refactor/BE] private 메서드 위치 변경
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
Labels: 🪢BE, REFACTOR

#413 [FIX/FE] DEMO DAY 에서 나온 버그 픽스 버전
  frontend/src/components/TopAppBar.tsx
  frontend/src/domains/admin/pages/agenda/create/index.tsx
  frontend/src/domains/admin/pages/opinion/entry/index.tsx
  frontend/src/domains/student/pages/agenda/index.tsx
  frontend/src/domains/student/pages/opinion/entry/index.tsx
  frontend/src/domains/student/pages/opinion/entry/styles.ts
  frontend/src/hooks/useImageUpload.ts
  frontend/src/index.css
Labels: 👔FE, 🛠️FIX

#414 [Hotfix/Be] signup npe
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
Labels: BUG🐛, 🪢BE

#416 [Hotfix/BE] 첫 회원가입 시 getUniversity npe 해결
  backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
  backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
Labels: BUG🐛, 🪢BE

#417 [FEAT/FE/365] 학생회 채팅방 리스트 중복 & 탭바 itemId 오류
  frontend/src/components/tab-bar/TabBar.tsx
  frontend/src/components/tab-bar/TabBarCotainer.tsx
  frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/admin/pages/agenda/index.tsx
  frontend/src/domains/admin/pages/opinion/chatroom/index.tsx
  frontend/src/domains/admin/pages/statistics/index.tsx
  frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx
  frontend/src/domains/student/pages/my/index.tsx
  frontend/src/domains/student/pages/opinion/chatroom/index.tsx
  frontend/src/hooks/useInfiniteScroll.tsx
  frontend/src/hooks/useScrollBottom.tsx
  frontend/src/stories/TabBarContainer.stories.tsx
  frontend/src/utils/chat/chat_const.ts
Labels: BUG🐛, 👔FE

#422 [Feat/BE/#420] 강제 종료 시 마지막 읽은 채팅 업데이트
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
Labels: 🪢BE

#423 [Fix/BE/#420] 마지막 읽은 채팅이 max인 값이 있을때만 update
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
Labels: BUG🐛, 🪢BE, STUDENT

#424 [Hotfix/BE/#420] 마지막 읽은 채팅이 Max값이 있을때만 update
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
Labels: BUG🐛, 🪢BE

#426 [Fix/BE] authorization 어노테이션 추가
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
Labels: 🪢BE, REFACTOR, 🛠️FIX

#429 [Fix/BE] accessor 누락 오류
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
Labels: BUG🐛, 🪢BE

#410 [BE] 마지막 스프린트
  backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AdminAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/MemberAgendaChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/auth/Claim.java
  backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java
  backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionCreationEvent.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
  backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
  backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java
  backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
  backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
  backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
  backend/src/test/java/com/bungeobbang/backend/admin/service/AdminLoginServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImplTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AdminAgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketConcurrencyTest.java
  backend/src/test/java/com/bungeobbang/backend/chat/AgendaWebSocketTest.java
  backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java
  backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
Labels: 🪢BE

#438 [Fix/Be] 통계 university 추가
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
  backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java
  backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
Labels: BUG🐛, 🪢BE

#461 [Fix/BE] agenda 조건문 오류 수정
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
Labels: BUG🐛, 🪢BE

#462 [Be] bug merge
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java
  backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
Labels: 🪢BE
